#' Download bam.
#'
#' @param gsm.df Dataframe contains GSM and Run numbers, obtained from \code{ExtractRun}.
#' @param out.folder Output folder. Default: NULL (current working directory).
#' @param download.method Method to download sra files, chosen from "prefetch", "download.file", "ascp".
#' Default: "prefetch".
#' @param bam.type The source of bam files to download, choose from 10x (e.g. CellRanger) or other.
#' Used when \code{download.method} is "prefetch". Default: 10x.
#' @param prefetch.path Path to prefetch. Default: NULL (conduct automatic detection).
#' @param prefetch.paras Parameters for \code{prefetch}. This should not contain --type or -T values. Default: "-X 100G".
#' @param samdump.path Path to sam-dump, used when \code{bam.type} is other. Default: NULL (conduct automatic detection).
#' @param samdump.paras Parameters for \code{sam-dump}. Default: "".
#' @param quiet Logical value, whether to show downloading progress. Used when \code{download.method} is "download.file".
#' Default: FALSE (show).
#' @param timeout Maximum request time. Used when \code{download.method} is "download.file". Default: 3600.
#' @param ascp.path Path to ascp (/path/bin/ascp), please ensure that the relative path of asperaweb_id_dsa.openssh file
#' (/path/bin/ascp/../etc/asperaweb_id_dsa.openssh). Default: NULL (conduct automatic detection).
#' @param max.rate Max transfer rate. Used when \code{download.method} is "ascp". Default: 300m.
#' @param rename Logical value, whether to rename the download sra files. Recommended when \code{download.method} is "ascp".
#' Default: FALSE (show).
#' @param parallel Logical value, whether to download parallelly. Used when \code{download.method} is "ascp" or "download.file".
#' Default: TRUE.
#' @param use.cores The number of cores used. Used when \code{download.method} is "ascp" or "download.file".
#' Default: NULL (the minimum value of \code{nrow(gsm.df)} and \code{parallel::detectCores()}).
#'
#' @return Dataframe contains failed runs or NULL.
#' @importFrom curl curl_fetch_memory
#' @importFrom magrittr %>%
#' @importFrom data.table fread
#' @importFrom dplyr filter
#' @importFrom tidyr separate_rows
#' @importFrom rlang .data
#' @importFrom parallel detectCores mclapply
#' @importFrom utils download.file
#' @export
#'
#' @examples
#' \dontrun{
#' GSE138266.runs <- ExtractRun(acce = "GSE138266", platform = "GPL18573")
#' # prefetch
#' GSE138266.down <- DownloadBam(
#'   gsm.df = GSE138266.runs, bam.type = "10x",
#'   prefetch.path = "/path/to/prefetch", out.folder = "/path/to/output"
#' )
#' # download.file
#' GSE138266.down <- DownloadBam(
#'   gsm.df = GSE138266.runs, download.method = "download.file",
#'   timeout = 3600, out.folder = "/path/to/output",
#'   parallel = TRUE, use.cores = 2
#' )
#' # ascp
#' GSE138266.down <- DownloadBam(
#'   gsm.df = GSE138266.runs, download.method = "ascp",
#'   ascp.path = "/path/to/ascp", max.rate = "300m",
#'   rename = TRUE, out.folder = "/path/to/output",
#'   parallel = TRUE, use.cores = 2
#' )
#' }
DownloadBam <- function(gsm.df, out.folder = NULL, download.method = c("prefetch", "download.file", "ascp"), bam.type = c("10x", "other"),
                        prefetch.path = NULL, prefetch.paras = "-X 100G", samdump.path = NULL, samdump.paras = "",
                        quiet = FALSE, timeout = 3600, ascp.path = NULL, max.rate = "300m", rename = TRUE, parallel = TRUE, use.cores = NULL) {
  # check parameters
  bam.type <- match.arg(arg = bam.type)
  download.method <- match.arg(arg = download.method)
  # check prefetch paras
  if (grepl(pattern = "--type|-T", x = prefetch.paras)) {
    stop("Please remomve --type|-T parameter in prefetch.paras!")
  }
  # check dataframe
  if (nrow(gsm.df) == 0) {
    stop("Please provide valid gsm.df!")
  }
  CheckColumns(df = gsm.df, columns = c("gsm_name", "run"))
  # prepare output folder
  if (is.null(out.folder)) {
    out.folder <- getwd()
  }
  # prepare sample output folder
  samples.folder <- file.path(out.folder, gsm.df$gsm_name)
  names(samples.folder) <- gsm.df$run
  # download
  if (download.method == "prefetch") {
    message("Download bam files with prefetch!")
    if (bam.type == "10x") {
      message("Download 10x original bam files (keep custom tags generated by 10x softwares)!")
      # add paras to download 10x original bam
      prefetch.paras <- paste0(prefetch.paras, " --type TenX ")
      bam.down <- DownloadSRA(
        gsm.df = gsm.df, out.folder = out.folder, download.method = "prefetch",
        prefetch.path = prefetch.path, prefetch.paras = prefetch.paras
      )
      return(bam.down)
    } else if (bam.type == "other") {
      message("Download normal bam files (non-10x), download sra first and convert to bam!")
      sra.down <- DownloadSRA(
        gsm.df = gsm.df, out.folder = out.folder, download.method = "prefetch",
        prefetch.path = prefetch.path, prefetch.paras = prefetch.paras
      )
      # convert sra to bam
      all.sras <- list.files(path = out.folder, pattern = "sra$", full.names = TRUE, recursive = TRUE)
      # get sam-dump path
      if (is.null(samdump.path)) {
        # specify sam-dump path
        samdump.path <- Sys.which("sam-dump")
        if (samdump.path == "") {
          stop("Can not find sam-dump automatically, please specify the path!")
        }
      } else {
        samdump.path <- samdump.path
      }
      # run sam-dump
      samdump.run <- sapply(all.sras, function(x) {
        RunSamdump(sra = x, samdump.path = samdump.path, samdump.paras = samdump.paras)
      })
      # select fail sras
      fail.flag <- sapply(names(samdump.run), function(x) {
        !is.null(samdump.run[[x]])
      })
      fail.sra <- names(samdump.run)[fail.flag]
      if (length(fail.sra) > 0) {
        fail.run <- gsub(pattern = ".sra$", replacement = "", x = basename(fail.sra))
        fail.df <- gsm.df[gsm.df$run %in% fail.run, ]
        if (!is.null(sra.down)) {
          fail.df <- as.data.frame(rbind(fail.df, sra.down))
          message(
            length(sra.down$run), " runs failed download and ", length(fail.sra), " sras failed to convert to bam.",
            "Return gsm.df, you can re-run with gsm.df!"
          )
        } else {
          message(
            length(fail.sra), " sras failed to convert to bam: ",
            paste0(fail.sra, collapse = ","), ". Return gsm.df, you can re-run with gsm.df!"
          )
        }
        return(fail.df)
      } else {
        if (!is.null(sra.down)) {
          fail.df <- sra.down
          message(
            length(sra.down$run), " runs failed download: ", paste0(sra.down$run, collapse = ","),
            ". Return gsm.df, you can re-run with gsm.df!"
          )
          return(fail.df)
        } else {
          message("All sra download and convert to bam successfully!")
          return(NULL)
        }
      }
    }
  } else {
    # parallel
    if (parallel) {
      cores.used <- min(parallel::detectCores(), nrow(gsm.df), use.cores)
      all.runs.down <- parallel::mclapply(X = 1:nrow(gsm.df), FUN = function(x) {
        gsm.df.x <- gsm.df[x, ]
        sf <- samples.folder[x]
        DownloadBamSingle(
          gsm.df = gsm.df.x, out.folder = sf, download.method = download.method,
          quiet = quiet, timeout = timeout, ascp.path = ascp.path, max.rate = max.rate, rename = rename
        )
      }, mc.cores = cores.used)
    } else {
      all.runs.down <- lapply(1:nrow(gsm.df), function(x) {
        gsm.df.x <- gsm.df[x, ]
        sf <- samples.folder[x]
        gsm.df.x <- gsm.df[x, ]
        sf <- samples.folder[x]
        DownloadBamSingle(
          gsm.df = gsm.df.x, out.folder = sf, download.method = download.method,
          quiet = quiet, timeout = timeout, ascp.path = ascp.path, max.rate = max.rate, rename = rename
        )
      })
    }
    # select fail samples
    fail.flag <- sapply(1:length(all.runs.down), function(x) {
      !is.null(all.runs.down[[x]])
    })
    fail.run <- unlist(all.runs.down[fail.flag])
    # return failed run
    if (length(fail.run) > 0) {
      fail.df <- gsm.df[gsm.df$run %in% fail.run, ]
      message(
        length(fail.run), " samples failed to download: ",
        paste0(fail.run, collapse = ","), ". Return dataframe contains failed samples, you can re-run!"
      )
      return(fail.df)
    } else {
      message("All samples downloaded successfully!")
      return(NULL)
    }
  }
}

# convert sra to bam files
RunSamdump <- function(sra, samdump.path, samdump.paras) {
  out.bam <- file.path(dirname(sra), gsub(pattern = "sra$", replacement = "bam", x = basename(sra)))
  # sam-dump command
  samdump.cmd <- paste(samdump.path, samdump.paras, sra, "| samtools view -bS - -o ", out.bam)
  # run command
  message(paste("Calling sam-dump:", samdump.cmd))
  samdump.status <- system(samdump.cmd, intern = TRUE)
  samdump.status.code <- attr(samdump.status, "status")
  if (!is.null(samdump.status.code)) {
    warning("Run sam-dump error on: ", sra, ", remove partial files!")
    file.remove(out.bam)
    return(sra)
  } else {
    message("Run sam-dump successful on: ", sra)
    return(NULL)
  }
}

# download bam from ena
DownloadBamSingle <- function(gsm.df, out.folder = NULL, download.method = c("download.file", "ascp"),
                              quiet = FALSE, timeout = 3600, ascp.path = NULL, max.rate = "300m", rename = TRUE) {
  # prepare output folder
  if (!dir.exists(out.folder)) {
    dir.create(path = out.folder, recursive = TRUE)
  }
  # download url prefix
  ftp.url.prefix <- "ftp://ftp.sra.ebi.ac.uk"
  ascp.url.prefix <- "era-fasp@fasp.sra.ebi.ac.uk:"
  # extract download file
  run.files.df <- ParseENAxml(run = gsm.df$run, df.type = "bam")
  if (is.null(run.files.df)) {
    return(gsm.df$run)
  } else {
    run.files.ftp <- paste0("ftp://", run.files.df$submitted_ftp)
    run.files.name <- basename(run.files.ftp)
    run.files.name <- gsub(pattern = ".bam.([0-9]+)$", replacement = "_\\1.bam", x = run.files.name)
    run.files.name <- gsub(pattern = ".bam.([0-9]+).bai$", replacement = "_\\1.bam.bai", x = run.files.name)
    # prepare urls
    if (download.method == "download.file") {
      download.urls <- run.files.ftp
    } else if (download.method == "ascp") {
      download.urls <- gsub(pattern = ftp.url.prefix, replacement = ascp.url.prefix, x = run.files.ftp)
    }
    # download
    download.res <- DownloadMethod(
      rn = gsm.df$run, url.vec = download.urls, name.vec = run.files.name,
      out.folder = out.folder, download.method = download.method, quiet = quiet,
      timeout = timeout, ascp.path = ascp.path, max.rate = max.rate, rename = rename
    )
    return(download.res)
  }
}

#' Convert bam files to fastq files.
#'
#' @param bam.folder Folder contains bam files, obtained from \code{DownloadSRA}. Default: NULL.
#' @param bam.path Paths of bams. \code{bam.folder} and \code{bam.path} cannot be both NULL. Default: NULL.
#' @param bam.type The source of bam files, choose from 10x (e.g. CellRanger) or other. Default: 10x.
#' @param pair.end The bam files are pair-end or single-end, used when \code{bam.type} is other. Default: NULL (identify with flag).
#' @param bamtofastq.path Path to 10x bamtofastq (\code{bam.type} is 10x) or samtools (\code{bam.type} is other).
#' Default: NULL (conduct automatic detection with bamtofastq_linux/samtools).
#' @param bamtofastq.paras Parameters for \code{bamtofastq.path}. Default: "--nthreads 4".
#' @param sort.name Logical value, whether the bam files are sorted by name, required when \code{bam.type} is other. Default: FALSE.
#' @param sort.thread The number of threads for bam sorting, used when \code{bam.type} is other. Default: 4.
#'
#' @return NULL or paths of failed bams.
#' @export
#'
#' @examples
#' \dontrun{
#' # need users to provide prefetch.path and bamtofastq.path
#' GSE138266.runs <- ExtractRun(acce = "GSE138266", platform = "GPL18573")
#' GSE138266.down <- DownloadBam(
#'   gsm.df = GSE138266.runs, prefetch.path = "/path/to/prefetch",
#'   out.folder = "/path/to/output"
#' )
#' GSE138266.convert <- Bam2Fastq(
#'   bam.folder = "/path/to/output",
#'   bamtofastq.path = "/path/to/bamtofastq_linux or samtools",
#'   bamtofastq.paras = "--nthreads 4"
#' )
#' }
Bam2Fastq <- function(bam.folder = NULL, bam.path = NULL, bam.type = c("10x", "other"), pair.end = NULL,
                      bamtofastq.path = NULL, bamtofastq.paras = "--nthreads 4", sort.name = FALSE, sort.thread = 4) {
  # check parameters
  bam.type <- match.arg(arg = bam.type)

  # get bamtofastq/samtools path
  if (is.null(bamtofastq.path)) {
    if (bam.type == "10x") {
      # specify bamtofastq path
      bamtofastq.path <- Sys.which("bamtofastq_linux")
    } else {
      # specify samtools path
      bamtofastq.path <- Sys.which("samtools")
    }
    if (bamtofastq.path == "") {
      stop("Can not find bamtofastq_linux/samtools automatically, please specify the path!")
    }
  } else {
    bamtofastq.path <- bamtofastq.path
  }
  # prepare bam files
  if (!is.null(bam.folder)) {
    all.bams <- list.files(path = bam.folder, pattern = "bam$", full.names = TRUE, recursive = TRUE)
  } else if (!is.null(bam.path)) {
    all.bams <- bam.path
  } else {
    stop("Please provide either valid bam.folder or bam.path!")
  }
  # check bams
  if (length(all.bams) == 0) {
    stop("There is no bam files detected. Please check!")
  }
  # run conversion
  all.bams.convert <- sapply(all.bams, function(x) {
    Runbamtofastq(
      bam.path = x, bam.type = bam.type, pair.end = pair.end, bamtofastq.path = bamtofastq.path,
      bamtofastq.paras = bamtofastq.paras, sort.name = sort.name, sort.thread = sort.thread
    )
  })
  # select fail bams
  fail.flag <- sapply(names(all.bams.convert), function(x) {
    !is.null(all.bams.convert[[x]])
  })
  fail.bam <- names(all.bams.convert)[fail.flag]
  # return
  if (length(fail.bam) > 0) {
    message(
      length(fail.bam), " runs failed to convert to fastqs: ",
      paste0(fail.bam, collapse = ","), ". Return paths, you can re-run with bam.path!"
    )
    return(fail.bam)
  } else {
    message("All bams convert successfully!")
    return(NULL)
  }
}

# convert bam to fastq: for 10x bam or general bam files
Runbamtofastq <- function(bam.path, bam.type, pair.end, bamtofastq.path, bamtofastq.paras, sort.name, sort.thread) {
  out.folder <- file.path(dirname(bam.path), "bam2fastq")
  # bamtofastq command
  if (bam.type == "10x") {
    bamtofastq.cmd <- paste(bamtofastq.path, bamtofastq.paras, bam.path, out.folder)
  } else if (bam.type == "other") {
    if (isFALSE(sort.name)) {
      sortn.bam <- gsub(pattern = ".bam$", replacement = ".sortname.bam", x = bam.path)
      bam.prefix <- gsub(pattern = ".bam$", replacement = "", x = basename(bam.path))
      sort.cmd <- paste(bamtofastq.path, "sort -@", sort.thread, "-T", bam.prefix, "-o", sortn.bam, bam.path)
      sort.status <- system(sort.cmd, intern = TRUE)
      bam.path <- sortn.bam
    }
    # check pair or single
    if (is.null(pair.end)) {
      bam.end <- CheckBam(bam = bam.path, samtools.path = bamtofastq.path)
    } else {
      bam.end <- pair.end
    }
    # create output folder
    if (!dir.exists(out.folder)) {
      dir.create(path = out.folder, recursive = TRUE)
    }
    if (bam.end) {
      fq1.name <- file.path(out.folder, gsub(pattern = ".bam$", replacement = "_1.fastq.gz", x = basename(bam.path)))
      fq2.name <- file.path(out.folder, gsub(pattern = ".bam$", replacement = "_2.fastq.gz", x = basename(bam.path)))
      bamtofastq.cmd <- paste(bamtofastq.path, "fastq", bamtofastq.paras, "-1", fq1.name, "-2", fq2.name, "-0 /dev/null -s /dev/null", bam.path)
    } else {
      pigz.path <- Sys.which("pigz")
      gzip.path <- Sys.which("gzip")
      if (pigz.path == "" && gzip.path == "") {
        message("There is no pigz and gzip detected, return fastq files!")
        fq.name <- file.path(out.folder, gsub(pattern = ".bam$", replacement = ".fastq", x = basename(bam.path)))
        bamtofastq.cmd <- paste(bamtofastq.path, "fastq", bamtofastq.paras, bam.path, "> ", fq.name)
      } else if (pigz.path != "") {
        message("Detected pigz, return fastq.gz files!")
        fq.name <- file.path(out.folder, gsub(pattern = ".bam$", replacement = ".fastq.gz", x = basename(bam.path)))
        bamtofastq.cmd <- paste(bamtofastq.path, "fastq", bamtofastq.paras, bam.path, "|pigz -p", sort.thread, "- >", fq.name)
      } else if (gzip.path != "") {
        message("Detected gzip, return fastq.gz files!")
        fq.name <- file.path(out.folder, gsub(pattern = ".bam$", replacement = ".fastq.gz", x = basename(bam.path)))
        bamtofastq.cmd <- paste(bamtofastq.path, "fastq", bamtofastq.paras, bam.path, "|gzip - >", fq.name)
      }
    }
  }
  # run command
  message(paste("Calling bamtofastq:", bamtofastq.cmd))
  bamtofastq.status <- system(bamtofastq.cmd, intern = TRUE)
  bamtofastq.status.code <- attr(bamtofastq.status, "status")
  if (!is.null(bamtofastq.status.code)) {
    warning("Run bamtofastq error on: ", bam.path, ", please remove ", out.folder, " and re-run!")
    return(bam.path)
  } else {
    message("Conversion successful: ", bam.path)
    return(NULL)
  }
}

# # convert bam to fastq: only for 10x
# Runbamtofastq <- function(bam.path, bamtofastq.path, bamtofastq.paras) {
#   out.folder <- file.path(dirname(bam.path), "bam2fastq")
#   # bamtofastq command
#   bamtofastq.cmd <- paste(bamtofastq.path, bamtofastq.paras, bam.path, out.folder)
#   # run command
#   message(paste("Calling bamtofastq:", bamtofastq.cmd))
#   bamtofastq.status <- system(bamtofastq.cmd, intern = TRUE)
#   bamtofastq.status.code <- attr(bamtofastq.status, "status")
#   if (!is.null(bamtofastq.status.code)) {
#     warning("Run bamtofastq error on: ", bam.path, ", please remove ", out.folder, " and re-run!")
#     return(bam.path)
#   } else {
#     message("Conversion successful: ", bam.path)
#     return(NULL)
#   }
# }
